# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust
# Default rust channel, but explicitly stated here for clarity
rust: stable


env:
  global:
    # Update this to match the name of your project.
    - PROJECT_NAME: fractious
addons:
  apt:
    packages:
      # For building MUSL static builds on Linux
      - musl-tools

matrix:
  fast_finish: true
  
  include:
    # Stable channel targets
    - os: linux
      env: TARGET=i686-unknown-linux-musl
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      
    - os: osx
      env: TARGET=x86_64-apple-darwin      

    - os: windows
      env: TARGET=x86_64-pc-windows-gnu

    # Test for regressions in beta channel, because we're helpful
    - os: linux
      env: TARGET=i686-unknown-linux-musl
      rust: beta
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      rust: beta

    # Test for issues in nightly channel, because we're helpful
    - os: linux
      env: TARGET=i686-unknown-linux-musl
      rust: nightly
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
  
before_install:
  - set -ex
  - rustup self update
  - rustup target add $TARGET
  - rustup component add clippy

script:
  - cargo clippy -- -D warnings
  - ci/script.sh

before_deploy: ci/before_deploy.sh

deploy:
  api_key:
    secure: "WF+jDIdR8BTc72alLMK84756hP+IYOyd8f51l7zw07sM3DW5JwO7Va8tEQX4Wv0T8LKQVCmi2l3YDuRX7quphJ2PI1APK+MD5YGq6MkgYMSCdQqZjV5BUawBiiZibjrcBYaR/7r3jIiPpE9ZXmAkZWxNGFqDU09euFryIok+aedwyI4GRy8ouXp+mBLei/ErkyDkGIW/+1TOHYWIPyt9N9WkAy0NDBYx/YzLAC66vVfFFR/sD1EIAUpYPb+gwQjseY1n/vV0KyGCuCy+O346IIeCDqBnJz6KCyHVZkD2g6eWDqnFxSN7XT6+Jf0YAKElZra3W4QkYk8pkuk9hY3LabMkl2biTUBlRL8LU1gH0HaPqKFycYMbOZYe0KBfCIT8dykGTbNZrNp3awcY5xZWszfBuIXgJuqALGQlSR7WM3V5ln2s+bDfCI83Ed0RnUtQ9IwfmnenSlinFu6OXG0HypvZPTpyqrq84//9SLco7T3Fc6QFkWoiWkSZjxBlb0dyBpCJeF8+t0z6rX+ZZJf8ottlZsID4taWZegIAhitdJl1KH6DqDIKtJ/yMJy0c+olMxDzURNft9OWdzq1KfKbCqSAcqf5nV09crWlgdg/VIfkKZAXRQcC3ZoZTWTjpi54s9qd9dFiJKLvC1IV7+6yH1Kt4qZzWTWLjI6xm7QyWCc="
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    # Commented out for testing purposes
    #tags: true
  provider: releases
  skip_cleanup: true
  draft: true
    
notifications:
  email:
    on_success: never
